/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiOrderChangeStateOrderPost$Json } from '../fn/order/api-order-change-state-order-post-json';
import { ApiOrderChangeStateOrderPost$Json$Params } from '../fn/order/api-order-change-state-order-post-json';
import { apiOrderChangeStateOrderPost$Plain } from '../fn/order/api-order-change-state-order-post-plain';
import { ApiOrderChangeStateOrderPost$Plain$Params } from '../fn/order/api-order-change-state-order-post-plain';
import { apiOrderCreatePost$Json } from '../fn/order/api-order-create-post-json';
import { ApiOrderCreatePost$Json$Params } from '../fn/order/api-order-create-post-json';
import { apiOrderCreatePost$Plain } from '../fn/order/api-order-create-post-plain';
import { ApiOrderCreatePost$Plain$Params } from '../fn/order/api-order-create-post-plain';
import { apiOrderGetOrderByIdGet$Json } from '../fn/order/api-order-get-order-by-id-get-json';
import { ApiOrderGetOrderByIdGet$Json$Params } from '../fn/order/api-order-get-order-by-id-get-json';
import { apiOrderGetOrderByIdGet$Plain } from '../fn/order/api-order-get-order-by-id-get-plain';
import { ApiOrderGetOrderByIdGet$Plain$Params } from '../fn/order/api-order-get-order-by-id-get-plain';
import { apiOrderGetRevenueLast7DaysGet$Json } from '../fn/order/api-order-get-revenue-last-7-days-get-json';
import { ApiOrderGetRevenueLast7DaysGet$Json$Params } from '../fn/order/api-order-get-revenue-last-7-days-get-json';
import { apiOrderGetRevenueLast7DaysGet$Plain } from '../fn/order/api-order-get-revenue-last-7-days-get-plain';
import { ApiOrderGetRevenueLast7DaysGet$Plain$Params } from '../fn/order/api-order-get-revenue-last-7-days-get-plain';
import { BooleanResultCustomModel } from '../models/boolean-result-custom-model';
import { OrderReponseResultCustomModel } from '../models/order-reponse-result-custom-model';
import { RevenueResponseListResultCustomModel } from '../models/revenue-response-list-result-custom-model';

@Injectable({ providedIn: 'root' })
export class OrderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiOrderCreatePost()` */
  static readonly ApiOrderCreatePostPath = '/api/Order/Create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain$Response(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderCreatePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Plain(params?: ApiOrderCreatePost$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderCreatePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderCreatePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json$Response(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderCreatePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderCreatePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiOrderCreatePost$Json(params?: ApiOrderCreatePost$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderCreatePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetOrderByIdGet()` */
  static readonly ApiOrderGetOrderByIdGetPath = '/api/Order/GetOrderById';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain$Response(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Plain(params?: ApiOrderGetOrderByIdGet$Plain$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetOrderByIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json$Response(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderReponseResultCustomModel>> {
    return apiOrderGetOrderByIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetOrderByIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetOrderByIdGet$Json(params?: ApiOrderGetOrderByIdGet$Json$Params, context?: HttpContext): Observable<OrderReponseResultCustomModel> {
    return this.apiOrderGetOrderByIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderReponseResultCustomModel>): OrderReponseResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderChangeStateOrderPost()` */
  static readonly ApiOrderChangeStateOrderPostPath = '/api/Order/ChangeStateOrder';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderChangeStateOrderPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Plain$Response(params?: ApiOrderChangeStateOrderPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderChangeStateOrderPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderChangeStateOrderPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Plain(params?: ApiOrderChangeStateOrderPost$Plain$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderChangeStateOrderPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderChangeStateOrderPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Json$Response(params?: ApiOrderChangeStateOrderPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanResultCustomModel>> {
    return apiOrderChangeStateOrderPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderChangeStateOrderPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderChangeStateOrderPost$Json(params?: ApiOrderChangeStateOrderPost$Json$Params, context?: HttpContext): Observable<BooleanResultCustomModel> {
    return this.apiOrderChangeStateOrderPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BooleanResultCustomModel>): BooleanResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiOrderGetRevenueLast7DaysGet()` */
  static readonly ApiOrderGetRevenueLast7DaysGetPath = '/api/Order/GetRevenueLast7Days';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetRevenueLast7DaysGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Plain$Response(params?: ApiOrderGetRevenueLast7DaysGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RevenueResponseListResultCustomModel>> {
    return apiOrderGetRevenueLast7DaysGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetRevenueLast7DaysGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Plain(params?: ApiOrderGetRevenueLast7DaysGet$Plain$Params, context?: HttpContext): Observable<RevenueResponseListResultCustomModel> {
    return this.apiOrderGetRevenueLast7DaysGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<RevenueResponseListResultCustomModel>): RevenueResponseListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiOrderGetRevenueLast7DaysGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Json$Response(params?: ApiOrderGetRevenueLast7DaysGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<RevenueResponseListResultCustomModel>> {
    return apiOrderGetRevenueLast7DaysGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiOrderGetRevenueLast7DaysGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiOrderGetRevenueLast7DaysGet$Json(params?: ApiOrderGetRevenueLast7DaysGet$Json$Params, context?: HttpContext): Observable<RevenueResponseListResultCustomModel> {
    return this.apiOrderGetRevenueLast7DaysGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<RevenueResponseListResultCustomModel>): RevenueResponseListResultCustomModel => r.body)
    );
  }

}
